### PR TITLE
Help people upgrade by distinguishing breaking changes

### PR DESCRIPTION
**Pull request by jaredbeck**
This is the format I use for my projects. It's nice to have
one, plain-text file that can easily be searched.

For other tips that I have found helpful, I recommed
http://keepachangelog.com

### CODE REVIEW

**Comment by twalpole** [comment]
@jaredbeck Thanks for this -- the reason there has been no changelog previously is that the user count for this gem (other than directly through Capybara, and very few people actually write custom Capybara selectors using the xpath gem,  though a lot would benefit from it) is really small.  Do you mind me asking exactly how you're using the xpath gem?

**Comment by jaredbeck** [comment]
> Do you mind me asking exactly how you're using the xpath gem?

Through capybara.

It's your call of course, but I find a changelog useful even for personal gems that no one else uses.

If you're concerned about not having time to maintain a changelog, that's fine, just make it clear at the top of the file that you won't be maintaining it and you'd like people to submit PRs.

> .. very few people actually write custom Capybara selectors using the xpath gem, though a lot would benefit from it ..

Interesting, I will take a closer look the next time I have a complicated DOM query.

**Comment by twalpole** [comment]
@jaredbeck It's worth looking into for relatively simple queries if there used a lot too.  Custom selectors can improve test readability and also help by limiting the specification of that query to one place so page changes becomes less painful.  Definitely worth looking into as you write new tests.  Thanks for the PR!

**Comment by jaredbeck** [comment]
> @jaredbeck It's worth looking into for relatively simple queries if they're used a lot too. Custom selectors can improve test readability and also help by limiting the specification of that query to one place so page changes becomes less painful.

Nice! Thanks for the tip.

**Pull request merged**
