### PR TITLE
Remove xpath/html

### PR DESCRIPTION
**Pull request by jnicklas**
This is obviously a hugely breaking change, and would necessitate bumping the major version to 3.0, but since these are no longer used by Capybara, I think it's just confusing to have them be part of the gem.

### CODE REVIEW

**Comment by TylerRick** [comment]
This is a hugely breaking change! :smile: I'm surprised no one has objected.

I just upgraded my xpath gem from a `bundle update` and started getting errors from code depending on `XPath::HTML`.

I can understand your reasons for removing this. Keeps this gem simple and focused.

Just wondering if there is a recommended upgrade path for those who want to keep using the nice selectors from `XPath::HTML`? Maybe they could be extracted to a `xpath-html` gem (I don't see one).

For now, I guess my workaround will just be:
```
wget -O lib/xpath/html.rb https://raw.githubusercontent.com/teamcapybara/xpath/bc99e5698d5a54facd7e95a737cec3be679b0ddc/lib/xpath/html.rb
```
```
require 'xpath/html'
```

**Comment by twalpole** [comment]
@TylerRick I'd say just copy the previous version of the file into your project if you still want it, or just lock to < 3.0 on the gem version.  If you don't mind me asking, what are you using them for?

**Comment by Ajedi32** [comment]
I personally found the HTML selectors very helpful when defining custom Capybara selectors. For example:

```
Capybara.add_selector(:select2_field) do
  # Find select2-container objects that point to fields with the given name
  xpath { |field_name| "#{XPath.css("div.select2-container")}[substring(./@id, 6) = (#{XPath.anywhere(XPath::HTML.field(field_name).attr(:id))})]" }
end
```

**Comment by twalpole** [comment]
@Ajedi32 Just an FYI -- you'd be better off returning an XPath::Expression from that rather than a string. Something like

    xpath { |field_name| XPath.css("div.select2-container")[XPath.attr(:id).substring(6) == XPath.anywhere(XPath::HTML.field(field_name).attr(:id))] }

**Comment by Ajedi32** [comment]
Funny story... I think enabling that exact line of code to return an XPath::Expression was actually my motivation for writing b9afe8a2d0f86cffd86b5bbbbc9ab44dee82db67 back in 2013. I just never got around to fixing it in the application after commit made it into a release. Thanks for the reminder. 😄

**Comment by TylerRick** [comment]
> If you don't mind me asking, what are you using them for?

Late response, but I was using them in custom selectors and things, similar to @Ajedi32.

I'd also added a `select_or_input` for cases where a field could be a `<select>` or an `<input>` (like `field` but excluding `textarea`):
```ruby
    def select_or_input(locator)
      locator = locator.to_s
      xpath = descendant(:input, :select)[~attr(:type).one_of('submit', 'image')]
      xpath = locate_field(xpath, locator)
      xpath
    end
```

**Pull request merged**
